#!/usr/bin/env bash
#MISE description="Build the project"
#MISE sources=["src/**/*"]
#MISE outputs=["dist/index.js", "dist/cli.js", "dist/command/", "dist/scripts/"]

bun build ./src/index.ts --outdir dist --target bun
bun build ./src/cli.ts --outdir dist --target bun
cp -r src/command dist/
cp -r scripts dist/